
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: it_management_db
    environment:
      POSTGRES_DB: it_management
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
